# 53 — Long-generation composition (greedy tier)

Tests whether blend, normalized score voting, and round-robin scheduling
retain their two-concept effects over the 200-step horizon selected in
`long-generation-inputs.yaml`. Each method is run at lambda 0 and 0.4.

The notebook is safe by default: it resolves and prints the complete run
matrix without loading model weights. Set `RUN_GENERATION = True` for a
smoke run or provide the printed confirmation string for the full matrix.
Existing JSONL logs are resumed by cell identity unless `OVERWRITE = True`.

In [1]:
# Papermill parameters
RUN_GENERATION = False
SMOKE = False
SMOKE_STEPS = 8
OVERWRITE = False
CONFIRM_FULL_RUN = ""
RUN_BENCHMARK = False
BENCHMARK_ONLY = False
RUN_TRAJECTORIES = False

In [2]:
# Parameters
RUN_GENERATION = True
SMOKE = False
OVERWRITE = False
CONFIRM_FULL_RUN = "RUN_53_450_CELLS"
RUN_BENCHMARK = False
BENCHMARK_ONLY = False
RUN_TRAJECTORIES = True

In [3]:
import json
import time
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import torch
from IPython.display import display

from frames.evaluation.harness import EvaluationHarness
from frames.experiments.long_generation import (
    generation_metadata,
    load_long_generation_experiment,
    token_bins,
)
from frames.experiments.notebook_helpers import llama_chat
from frames.linalg.angles import vector_subspace_cosine
from frames.representations import FrameUnembeddingRepresentation
from frames.representations.concept import Concept
from frames.representations.schedulers import RoundRobin

CONFIG_PATH = Path("long-generation-inputs.yaml")
EXPERIMENT = load_long_generation_experiment(CONFIG_PATH, "experiment_53")

MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"
MODEL_KEY = "llama-3.1-8b-bf16"
MIN_LEMMAS = 11
MAX_TOKENS = 3
K = 4
METHODS = ("blend", "vote", "schedule")
BIN_WIDTH = 20

prompts_by_id = {
    row["id"]: llama_chat(row["user"], row["assistant_prefix"])
    for row in EXPERIMENT.prompts
}
active_prompts = list(EXPERIMENT.prompts)
active_pairs = list(EXPERIMENT.composition_pairs)
active_lambdas = list(EXPERIMENT.lambdas)
run_steps = EXPERIMENT.steps
if SMOKE:
    active_prompts = active_prompts[:1]
    active_pairs = active_pairs[:1]
    run_steps = min(SMOKE_STEPS, EXPERIMENT.steps)

full_cells = EXPERIMENT.guided_run_count(len(METHODS))
active_cells = (
    len(active_prompts) * len(active_pairs) * len(METHODS) * len(active_lambdas)
)
confirmation = f"RUN_53_{full_cells}_CELLS"
print(
    f"full matrix: {len(EXPERIMENT.composition_pairs)} pairs x "
    f"{len(EXPERIMENT.prompts)} prompts x {len(METHODS)} methods x "
    f"{len(EXPERIMENT.lambdas)} lambdas = {full_cells} guided continuations"
)
print(
    f"nominal full token budget: "
    f"{EXPERIMENT.output_token_budget(len(METHODS)):,} (early EOS excluded)"
)
print(
    f"this execution: {active_cells} cells at steps={run_steps}; "
    f"SMOKE={SMOKE}, RUN_GENERATION={RUN_GENERATION}"
)
print(f"full-run confirmation: {confirmation}")

if (
    RUN_GENERATION
    and not SMOKE
    and not BENCHMARK_ONLY
    and CONFIRM_FULL_RUN != confirmation
):
    raise RuntimeError(
        "Full generation is locked. Set CONFIRM_FULL_RUN to the printed string."
    )
if BENCHMARK_ONLY and not RUN_BENCHMARK:
    raise ValueError("BENCHMARK_ONLY requires RUN_BENCHMARK=True")
if SMOKE_STEPS < 1:
    raise ValueError("SMOKE_STEPS must be positive")

full matrix: 15 pairs x 5 prompts x 3 methods x 2 lambdas = 450 guided continuations
nominal full token budget: 90,000 (early EOS excluded)
this execution: 450 cells at steps=200; SMOKE=False, RUN_GENERATION=True
full-run confirmation: RUN_53_450_CELLS

In [4]:
suffix = "_smoke" if SMOKE else ""
LOG_PATH = Path(f"resources/53_long_composition{suffix}.jsonl")
BASELINE_PATH = Path(f"resources/53_long_composition_baselines{suffix}.json")
SUMMARY_PATH = Path(f"resources/53_long_composition_summary{suffix}.csv")
TRAJECTORY_PATH = Path(
    f"resources/53_long_composition_trajectories{suffix}.csv"
)
TRAJECTORY_FIGURE_PATH = Path(
    f"resources/53_long_composition_trajectories{suffix}.png"
)
FIGURE_PATH = Path(f"resources/53_long_composition_metrics{suffix}.png")
TIMING_PATH = Path("resources/53_long_composition_timing.csv")

def read_records(path):
    if not path.exists() or not path.read_text().strip():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line]


def record_key(config):
    return (
        config["pair_id"],
        config["prompt_id"],
        config["method"],
        float(config["lam"]),
        int(config["steps"]),
    )


if RUN_GENERATION and OVERWRITE:
    for path in (LOG_PATH, BASELINE_PATH, SUMMARY_PATH, TRAJECTORY_PATH):
        path.unlink(missing_ok=True)

planned = {
    (pair["id"], prompt["id"], method, float(lam), run_steps)
    for pair in active_pairs
    for prompt in active_prompts
    for method in METHODS
    for lam in active_lambdas
}
completed = {record_key(row["config"]) for row in read_records(LOG_PATH)}
unexpected = completed - planned
if unexpected:
    raise RuntimeError(
        f"{LOG_PATH} contains {len(unexpected)} cells outside the resolved "
        "matrix; preserve it and start a new artifact or use OVERWRITE=True"
    )
print(f"resume state: {len(completed)}/{active_cells} active cells already logged")

resume state: 0/450 active cells already logged

## Model, concepts, and shared baselines

The model is loaded only for generation or the optional longitudinal
analysis. Baselines are versioned by model, prompt text, and run horizon.
A stale baseline cache is rejected instead of silently reused.

In [5]:
need_model = RUN_GENERATION or RUN_TRAJECTORIES
fur = harness = None
concepts = {}
baseline_texts_by_id = {}

if need_model:
    fur = FrameUnembeddingRepresentation.from_model_id(
        id=MODEL_ID, device_map="auto", torch_dtype=torch.bfloat16
    )
    harness = EvaluationHarness(
        fur,
        LOG_PATH,
        min_lemmas_per_synset=MIN_LEMMAS,
        max_token_count=MAX_TOKENS,
    )

    used_synsets = sorted(
        {name for pair in active_pairs for name in (pair["a"], pair["b"])}
    )
    for name in used_synsets:
        cached = fur.get_concept_cached(name, MIN_LEMMAS, MAX_TOKENS)
        concepts[name] = Concept(
            synset=cached.synset, tensor=cached.tensor.to(fur.model.device)
        )
    print(f"loaded {len(concepts)} cached concepts")

    need_baselines = (RUN_GENERATION and not BENCHMARK_ONLY) or RUN_TRAJECTORIES
    if need_baselines:
        baseline_spec = {
            "model": MODEL_KEY,
            "steps": run_steps,
            "max_new_tokens": run_steps + 1,
            "prompts": {
                row["id"]: prompts_by_id[row["id"]]
                for row in active_prompts
            },
        }
        if BASELINE_PATH.exists():
            baseline_payload = json.loads(BASELINE_PATH.read_text())
            if baseline_payload.get("spec") != baseline_spec:
                raise RuntimeError(
                    f"{BASELINE_PATH} does not match this run; use OVERWRITE=True"
                )
            baseline_texts_by_id = baseline_payload["texts"]
            print(f"reused {len(baseline_texts_by_id)} baselines")
        elif RUN_GENERATION:
            for prompt_row in active_prompts:
                prompt_id = prompt_row["id"]
                baseline_texts_by_id[prompt_id] = harness.generate_baseline(
                    [prompts_by_id[prompt_id]], max_new_tokens=run_steps + 1
                )[0]
            BASELINE_PATH.write_text(
                json.dumps(
                    {"spec": baseline_spec, "texts": baseline_texts_by_id},
                    indent=2,
                    ensure_ascii=False,
                )
                + "\n"
            )
            print(f"wrote {BASELINE_PATH}")
        else:
            raise FileNotFoundError(
                f"RUN_TRAJECTORIES requires an existing {BASELINE_PATH}"
            )
else:
    print("model load skipped")

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

2026-08-09 22:07:39.260 | INFO     | frames.models.hf.base:__init__:88 - Loaded model: meta-llama/Llama-3.1-8B-Instruct

2026-08-09 22:07:39.262 | WARNING  | frames.models.hf.base:__init__:89 - memory cost: 15316 Mb

loaded 18 cached concepts

  0%|                                                     | 0/1 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.87s/it]

100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.87s/it]

  0%|                                                     | 0/1 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.46s/it]

100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.46s/it]

  0%|                                                     | 0/1 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.12s/it]

100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.12s/it]

  0%|                                                     | 0/1 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.48s/it]

100%|█████████████████████████████████████████████| 1/1 [00:05<00:00,  5.48s/it]

  0%|                                                     | 0/1 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.30s/it]

100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.31s/it]

wrote resources/53_long_composition_baselines.json

In [6]:
# Optional preflight benchmark. It is deliberately outside the main log.
if RUN_GENERATION and RUN_BENCHMARK:
    pair = active_pairs[0]
    prompt_row = active_prompts[0]
    ca, cb = concepts[pair["a"]], concepts[pair["b"]]
    guide = Concept.average([ca, cb])
    benchmark_rows = []
    for benchmark_steps in (24, 50, 100):
        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()
        started = time.perf_counter()
        text, _ = fur.generate_with_topk_multi_guide(
            [prompts_by_id[prompt_row["id"]]],
            guides=[guide],
            k=K,
            steps=benchmark_steps,
            fluency_weight=0.4,
            batch_size=1,
        )
        elapsed = time.perf_counter() - started
        continuation = harness.continuation(
            text[0], prompts_by_id[prompt_row["id"]]
        )
        meta = generation_metadata(
            fur.model.tokenizer, continuation, benchmark_steps, elapsed
        )
        benchmark_rows.append(
            {
                "steps": benchmark_steps,
                "elapsed_seconds": elapsed,
                "seconds_per_output_token": elapsed / max(meta["token_count"], 1),
                "continuation_tokens": meta["token_count"],
                "peak_cuda_gib": (
                    torch.cuda.max_memory_allocated() / 2**30
                    if torch.cuda.is_available()
                    else float("nan")
                ),
            }
        )
    benchmark = pd.DataFrame(benchmark_rows)
    benchmark.to_csv(TIMING_PATH, index=False)
    display(benchmark.round(3))

## Guided run

Each cell is generated and logged independently (`batch_size=1`). This is
conservative for the long context and makes interruption/resume exact. The
paper's greedy survivor rule is unchanged; only guide, score, or active
concept differs across the three methods.

In [7]:
FAMILY = {"blend": "frame", "vote": "score", "schedule": "time"}

def make_methods(prompt, pair, lam):
    ca, cb = concepts[pair["a"]], concepts[pair["b"]]
    blend_guide = Concept.average([ca, cb])
    return {
        "blend": lambda: fur.generate_with_topk_multi_guide(
            [prompt],
            guides=[blend_guide],
            k=K,
            steps=run_steps,
            fluency_weight=lam,
            batch_size=1,
        ),
        "vote": lambda: fur.generate_with_topk_multi_guide(
            [prompt],
            guides=[ca, cb],
            k=K,
            steps=run_steps,
            normalize="zscore",
            fluency_weight=lam,
            batch_size=1,
        ),
        "schedule": lambda: fur.generate_with_topk_multi_guide(
            [prompt],
            guides=[ca, cb],
            k=K,
            steps=run_steps,
            scorer=RoundRobin(),
            fluency_weight=lam,
            batch_size=1,
        ),
    }


if RUN_GENERATION and not BENCHMARK_ONLY:
    for pair in active_pairs:
        ca, cb = concepts[pair["a"]], concepts[pair["b"]]
        measured_rho = float(ca.rho(cb))
        for prompt_row in active_prompts:
            prompt_id = prompt_row["id"]
            prompt = prompts_by_id[prompt_id]
            for lam in active_lambdas:
                methods = make_methods(prompt, pair, lam)
                for method in METHODS:
                    key = (pair["id"], prompt_id, method, float(lam), run_steps)
                    if key in completed:
                        continue
                    torch.cuda.empty_cache()
                    started = time.perf_counter()
                    texts, probe = methods[method]()
                    elapsed = time.perf_counter() - started
                    continuation = harness.continuation(texts[0], prompt)
                    metadata = generation_metadata(
                        fur.model.tokenizer, continuation, run_steps, elapsed
                    )
                    harness.evaluate(
                        [prompt],
                        texts,
                        [pair["a"], pair["b"]],
                        config={
                            "experiment": "53",
                            "model": MODEL_KEY,
                            "pair_id": pair["id"],
                            "prompt_id": prompt_id,
                            "method": method,
                            "family": FAMILY[method],
                            "lam": float(lam),
                            "a": pair["a"],
                            "b": pair["b"],
                            "rho_catalog": float(pair["rho"]),
                            "rho_model": measured_rho,
                            "k": K,
                            "steps": run_steps,
                            "survivor_rule": "greedy",
                        },
                        probe=probe,
                        baseline_texts=[baseline_texts_by_id[prompt_id]],
                        concepts={pair["a"]: ca, pair["b"]: cb},
                        angles=True,
                        metadata=[metadata],
                    )
                    completed.add(key)
                    print(
                        f"{len(completed):>3}/{active_cells} "
                        f"{pair['id']} / {prompt_id} / {method} / "
                        f"lambda={lam}: {metadata['token_count']} tokens, "
                        f"{elapsed:.1f}s"
                    )

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.54s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.54s/it]

  1/450 education_sorrow / short_story / blend / lambda=0.0: 202 tokens, 24.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.93s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.93s/it]

  2/450 education_sorrow / short_story / vote / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.25s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.25s/it]

  3/450 education_sorrow / short_story / schedule / lambda=0.0: 200 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.08s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.08s/it]

  4/450 education_sorrow / short_story / blend / lambda=0.4: 202 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.99s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.99s/it]

  5/450 education_sorrow / short_story / vote / lambda=0.4: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.76s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.76s/it]

  6/450 education_sorrow / short_story / schedule / lambda=0.4: 200 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

  7/450 education_sorrow / favorite_place / blend / lambda=0.0: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.76s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.76s/it]

  8/450 education_sorrow / favorite_place / vote / lambda=0.0: 31 tokens, 11.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

  9/450 education_sorrow / favorite_place / schedule / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.23s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.23s/it]

 10/450 education_sorrow / favorite_place / blend / lambda=0.4: 100 tokens, 21.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.87s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.87s/it]

 11/450 education_sorrow / favorite_place / vote / lambda=0.4: 33 tokens, 11.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.11s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.11s/it]

 12/450 education_sorrow / favorite_place / schedule / lambda=0.4: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.74s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.74s/it]

 13/450 education_sorrow / weekends / blend / lambda=0.0: 74 tokens, 18.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.71s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.71s/it]

 14/450 education_sorrow / weekends / vote / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.27s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.27s/it]

 15/450 education_sorrow / weekends / schedule / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.70s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.70s/it]

 16/450 education_sorrow / weekends / blend / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

 17/450 education_sorrow / weekends / vote / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.35s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.35s/it]

 18/450 education_sorrow / weekends / schedule / lambda=0.4: 97 tokens, 21.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.17s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.17s/it]

 19/450 education_sorrow / good_life / blend / lambda=0.0: 203 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.07s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.07s/it]

 20/450 education_sorrow / good_life / vote / lambda=0.0: 203 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.12s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.13s/it]

 21/450 education_sorrow / good_life / schedule / lambda=0.0: 203 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.11s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.11s/it]

 22/450 education_sorrow / good_life / blend / lambda=0.4: 203 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.17s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.17s/it]

 23/450 education_sorrow / good_life / vote / lambda=0.4: 203 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.13s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.13s/it]

 24/450 education_sorrow / good_life / schedule / lambda=0.4: 203 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.83s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.84s/it]

 25/450 education_sorrow / weather / blend / lambda=0.0: 205 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.84s/it]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.84s/it]

 26/450 education_sorrow / weather / vote / lambda=0.0: 39 tokens, 12.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.88s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.88s/it]

 27/450 education_sorrow / weather / schedule / lambda=0.0: 205 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.09s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.09s/it]

 28/450 education_sorrow / weather / blend / lambda=0.4: 144 tokens, 24.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:14<00:00, 14.20s/it]

100%|█████████████████████████████████████████████| 1/1 [00:14<00:00, 14.20s/it]

 29/450 education_sorrow / weather / vote / lambda=0.4: 52 tokens, 14.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.89s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.89s/it]

 30/450 education_sorrow / weather / schedule / lambda=0.4: 203 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:23<00:00, 23.52s/it]

100%|█████████████████████████████████████████████| 1/1 [00:23<00:00, 23.52s/it]

 31/450 fuss_education / short_story / blend / lambda=0.0: 117 tokens, 23.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:23<00:00, 23.81s/it]

100%|█████████████████████████████████████████████| 1/1 [00:23<00:00, 23.81s/it]

 32/450 fuss_education / short_story / vote / lambda=0.0: 138 tokens, 23.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.43s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.43s/it]

 33/450 fuss_education / short_story / schedule / lambda=0.0: 201 tokens, 25.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.53s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.53s/it]

 34/450 fuss_education / short_story / blend / lambda=0.4: 202 tokens, 25.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.87s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.88s/it]

 35/450 fuss_education / short_story / vote / lambda=0.4: 149 tokens, 24.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.60s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.60s/it]

 36/450 fuss_education / short_story / schedule / lambda=0.4: 202 tokens, 25.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.96s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.96s/it]

 37/450 fuss_education / favorite_place / blend / lambda=0.0: 205 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.74s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.74s/it]

 38/450 fuss_education / favorite_place / vote / lambda=0.0: 33 tokens, 11.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

 39/450 fuss_education / favorite_place / schedule / lambda=0.0: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

 40/450 fuss_education / favorite_place / blend / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.95s/it]

 41/450 fuss_education / favorite_place / vote / lambda=0.4: 38 tokens, 12.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

 42/450 fuss_education / favorite_place / schedule / lambda=0.4: 204 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

 43/450 fuss_education / weekends / blend / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.83s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

 44/450 fuss_education / weekends / vote / lambda=0.0: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.47s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.47s/it]

 45/450 fuss_education / weekends / schedule / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.51s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.51s/it]

 46/450 fuss_education / weekends / blend / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.34s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.34s/it]

 47/450 fuss_education / weekends / vote / lambda=0.4: 67 tokens, 18.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.64s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.64s/it]

 48/450 fuss_education / weekends / schedule / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.31s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.31s/it]

 49/450 fuss_education / good_life / blend / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

 50/450 fuss_education / good_life / vote / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.36s/it]

 51/450 fuss_education / good_life / schedule / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.37s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.37s/it]

 52/450 fuss_education / good_life / blend / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.41s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.41s/it]

 53/450 fuss_education / good_life / vote / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

 54/450 fuss_education / good_life / schedule / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

 55/450 fuss_education / weather / blend / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.06s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.06s/it]

 56/450 fuss_education / weather / vote / lambda=0.0: 119 tokens, 24.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.19s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.19s/it]

 57/450 fuss_education / weather / schedule / lambda=0.0: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.21s/it]

 58/450 fuss_education / weather / blend / lambda=0.4: 204 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.05s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.05s/it]

 59/450 fuss_education / weather / vote / lambda=0.4: 66 tokens, 18.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

 60/450 fuss_education / weather / schedule / lambda=0.4: 204 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.79s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.79s/it]

 61/450 benefit_education / short_story / blend / lambda=0.0: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.04s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.05s/it]

 62/450 benefit_education / short_story / vote / lambda=0.0: 136 tokens, 24.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.88s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.88s/it]

 63/450 benefit_education / short_story / schedule / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.78s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.78s/it]

 64/450 benefit_education / short_story / blend / lambda=0.4: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.71s/it]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.71s/it]

 65/450 benefit_education / short_story / vote / lambda=0.4: 94 tokens, 20.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.97s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.97s/it]

 66/450 benefit_education / short_story / schedule / lambda=0.4: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

 67/450 benefit_education / favorite_place / blend / lambda=0.0: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:07<00:00,  7.93s/it]

100%|█████████████████████████████████████████████| 1/1 [00:07<00:00,  7.93s/it]

 68/450 benefit_education / favorite_place / vote / lambda=0.0: 9 tokens, 7.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

 69/450 benefit_education / favorite_place / schedule / lambda=0.0: 204 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.21s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.21s/it]

 70/450 benefit_education / favorite_place / blend / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.18s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.18s/it]

 71/450 benefit_education / favorite_place / vote / lambda=0.4: 120 tokens, 24.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.24s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.24s/it]

 72/450 benefit_education / favorite_place / schedule / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.95s/it]

 73/450 benefit_education / weekends / blend / lambda=0.0: 203 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.01s/it]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.01s/it]

 74/450 benefit_education / weekends / vote / lambda=0.0: 73 tokens, 19.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.98s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.98s/it]

 75/450 benefit_education / weekends / schedule / lambda=0.0: 203 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.69s/it]

 76/450 benefit_education / weekends / blend / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.86s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.86s/it]

 77/450 benefit_education / weekends / vote / lambda=0.4: 203 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

 78/450 benefit_education / weekends / schedule / lambda=0.4: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.51s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.51s/it]

 79/450 benefit_education / good_life / blend / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

 80/450 benefit_education / good_life / vote / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

 81/450 benefit_education / good_life / schedule / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.60s/it]

 82/450 benefit_education / good_life / blend / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.64s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

 83/450 benefit_education / good_life / vote / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.62s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.62s/it]

 84/450 benefit_education / good_life / schedule / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.32s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.32s/it]

 85/450 benefit_education / weather / blend / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.31s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.31s/it]

 86/450 benefit_education / weather / vote / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

 87/450 benefit_education / weather / schedule / lambda=0.0: 204 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.54s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

 88/450 benefit_education / weather / blend / lambda=0.4: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.20s/it]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.20s/it]

 89/450 benefit_education / weather / vote / lambda=0.4: 83 tokens, 19.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.51s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.52s/it]

 90/450 benefit_education / weather / schedule / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.27s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.27s/it]

 91/450 cattle_town / short_story / blend / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.19s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.19s/it]

 92/450 cattle_town / short_story / vote / lambda=0.0: 141 tokens, 24.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.94s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.94s/it]

 93/450 cattle_town / short_story / schedule / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.10s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.10s/it]

 94/450 cattle_town / short_story / blend / lambda=0.4: 202 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.81s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.81s/it]

 95/450 cattle_town / short_story / vote / lambda=0.4: 77 tokens, 18.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.04s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.04s/it]

 96/450 cattle_town / short_story / schedule / lambda=0.4: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

 97/450 cattle_town / favorite_place / blend / lambda=0.0: 205 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.82s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.82s/it]

 98/450 cattle_town / favorite_place / vote / lambda=0.0: 31 tokens, 11.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.81s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.81s/it]

 99/450 cattle_town / favorite_place / schedule / lambda=0.0: 205 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.45s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.46s/it]

100/450 cattle_town / favorite_place / blend / lambda=0.4: 132 tokens, 24.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:08<00:00,  8.60s/it]

100%|█████████████████████████████████████████████| 1/1 [00:08<00:00,  8.60s/it]

101/450 cattle_town / favorite_place / vote / lambda=0.4: 20 tokens, 8.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

102/450 cattle_town / favorite_place / schedule / lambda=0.4: 205 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

103/450 cattle_town / weekends / blend / lambda=0.0: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.35s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.35s/it]

104/450 cattle_town / weekends / vote / lambda=0.0: 80 tokens, 21.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.10s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.10s/it]

105/450 cattle_town / weekends / schedule / lambda=0.0: 204 tokens, 27.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.99s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.99s/it]

106/450 cattle_town / weekends / blend / lambda=0.4: 203 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.40s/it]

107/450 cattle_town / weekends / vote / lambda=0.4: 82 tokens, 21.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.32s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.33s/it]

108/450 cattle_town / weekends / schedule / lambda=0.4: 203 tokens, 27.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.63s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.63s/it]

109/450 cattle_town / good_life / blend / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.63s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.63s/it]

110/450 cattle_town / good_life / vote / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.68s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.68s/it]

111/450 cattle_town / good_life / schedule / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.62s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.62s/it]

112/450 cattle_town / good_life / blend / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.68s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.68s/it]

113/450 cattle_town / good_life / vote / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

114/450 cattle_town / good_life / schedule / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

115/450 cattle_town / weather / blend / lambda=0.0: 205 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.53s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.53s/it]

116/450 cattle_town / weather / vote / lambda=0.0: 100 tokens, 21.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.40s/it]

117/450 cattle_town / weather / schedule / lambda=0.0: 212 tokens, 27.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.37s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.37s/it]

118/450 cattle_town / weather / blend / lambda=0.4: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:15<00:00, 15.67s/it]

100%|█████████████████████████████████████████████| 1/1 [00:15<00:00, 15.67s/it]

119/450 cattle_town / weather / vote / lambda=0.4: 69 tokens, 15.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

120/450 cattle_town / weather / schedule / lambda=0.4: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.93s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.93s/it]

121/450 end_jail / short_story / blend / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.91s/it]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.91s/it]

122/450 end_jail / short_story / vote / lambda=0.0: 53 tokens, 16.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.08s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.08s/it]

123/450 end_jail / short_story / schedule / lambda=0.0: 202 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.95s/it]

124/450 end_jail / short_story / blend / lambda=0.4: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.74s/it]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.74s/it]

125/450 end_jail / short_story / vote / lambda=0.4: 91 tokens, 20.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.06s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.06s/it]

126/450 end_jail / short_story / schedule / lambda=0.4: 201 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.95s/it]

127/450 end_jail / favorite_place / blend / lambda=0.0: 205 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.11s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.11s/it]

128/450 end_jail / favorite_place / vote / lambda=0.0: 66 tokens, 18.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

129/450 end_jail / favorite_place / schedule / lambda=0.0: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.23s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.23s/it]

130/450 end_jail / favorite_place / blend / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.62s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.62s/it]

131/450 end_jail / favorite_place / vote / lambda=0.4: 59 tokens, 13.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.42s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.42s/it]

132/450 end_jail / favorite_place / schedule / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.22s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.22s/it]

133/450 end_jail / weekends / blend / lambda=0.0: 203 tokens, 27.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.22s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.22s/it]

134/450 end_jail / weekends / vote / lambda=0.0: 38 tokens, 13.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.09s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.09s/it]

135/450 end_jail / weekends / schedule / lambda=0.0: 202 tokens, 27.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.82s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.82s/it]

136/450 end_jail / weekends / blend / lambda=0.4: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.42s/it]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.42s/it]

137/450 end_jail / weekends / vote / lambda=0.4: 55 tokens, 17.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.93s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.93s/it]

138/450 end_jail / weekends / schedule / lambda=0.4: 99 tokens, 21.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.72s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.72s/it]

139/450 end_jail / good_life / blend / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.60s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.60s/it]

140/450 end_jail / good_life / vote / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

141/450 end_jail / good_life / schedule / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.61s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.61s/it]

142/450 end_jail / good_life / blend / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.69s/it]

143/450 end_jail / good_life / vote / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

144/450 end_jail / good_life / schedule / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

145/450 end_jail / weather / blend / lambda=0.0: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.24s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.24s/it]

146/450 end_jail / weather / vote / lambda=0.0: 117 tokens, 24.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

147/450 end_jail / weather / schedule / lambda=0.0: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.13s/it]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.13s/it]

148/450 end_jail / weather / blend / lambda=0.4: 81 tokens, 19.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.37s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.37s/it]

149/450 end_jail / weather / vote / lambda=0.4: 117 tokens, 24.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

150/450 end_jail / weather / schedule / lambda=0.4: 169 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.91s/it]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.92s/it]

151/450 end_country / short_story / blend / lambda=0.0: 54 tokens, 16.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.99s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.99s/it]

152/450 end_country / short_story / vote / lambda=0.0: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.91s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.91s/it]

153/450 end_country / short_story / schedule / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.88s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.88s/it]

154/450 end_country / short_story / blend / lambda=0.4: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.84s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.85s/it]

155/450 end_country / short_story / vote / lambda=0.4: 201 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.90s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.90s/it]

156/450 end_country / short_story / schedule / lambda=0.4: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.18s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.18s/it]

157/450 end_country / favorite_place / blend / lambda=0.0: 204 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.68s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.68s/it]

158/450 end_country / favorite_place / vote / lambda=0.0: 22 tokens, 11.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.32s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.32s/it]

159/450 end_country / favorite_place / schedule / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.90s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.90s/it]

160/450 end_country / favorite_place / blend / lambda=0.4: 77 tokens, 18.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.26s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.26s/it]

161/450 end_country / favorite_place / vote / lambda=0.4: 44 tokens, 13.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.05s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.05s/it]

162/450 end_country / favorite_place / schedule / lambda=0.4: 110 tokens, 21.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.84s/it]

163/450 end_country / weekends / blend / lambda=0.0: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.23s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.23s/it]

164/450 end_country / weekends / vote / lambda=0.0: 64 tokens, 18.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.88s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.89s/it]

165/450 end_country / weekends / schedule / lambda=0.0: 203 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.72s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.72s/it]

166/450 end_country / weekends / blend / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.21s/it]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.21s/it]

167/450 end_country / weekends / vote / lambda=0.4: 78 tokens, 19.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

168/450 end_country / weekends / schedule / lambda=0.4: 201 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.46s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.46s/it]

169/450 end_country / good_life / blend / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

170/450 end_country / good_life / vote / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.53s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.53s/it]

171/450 end_country / good_life / schedule / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.54s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

172/450 end_country / good_life / blend / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.57s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.57s/it]

173/450 end_country / good_life / vote / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

174/450 end_country / good_life / schedule / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.45s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.45s/it]

175/450 end_country / weather / blend / lambda=0.0: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.15s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.15s/it]

176/450 end_country / weather / vote / lambda=0.0: 41 tokens, 13.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.26s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.26s/it]

177/450 end_country / weather / schedule / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.27s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.27s/it]

178/450 end_country / weather / blend / lambda=0.4: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

179/450 end_country / weather / vote / lambda=0.4: 199 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.28s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.28s/it]

180/450 end_country / weather / schedule / lambda=0.4: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.87s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.87s/it]

181/450 respite_universe / short_story / blend / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.29s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.29s/it]

182/450 respite_universe / short_story / vote / lambda=0.0: 207 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.93s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.93s/it]

183/450 respite_universe / short_story / schedule / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.91s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.91s/it]

184/450 respite_universe / short_story / blend / lambda=0.4: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.86s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.86s/it]

185/450 respite_universe / short_story / vote / lambda=0.4: 201 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.95s/it]

186/450 respite_universe / short_story / schedule / lambda=0.4: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

187/450 respite_universe / favorite_place / blend / lambda=0.0: 205 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:07<00:00,  7.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:07<00:00,  7.95s/it]

188/450 respite_universe / favorite_place / vote / lambda=0.0: 9 tokens, 8.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.25s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.25s/it]

189/450 respite_universe / favorite_place / schedule / lambda=0.0: 204 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.69s/it]

190/450 respite_universe / favorite_place / blend / lambda=0.4: 205 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.19s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.19s/it]

191/450 respite_universe / favorite_place / vote / lambda=0.4: 40 tokens, 13.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.51s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.51s/it]

192/450 respite_universe / favorite_place / schedule / lambda=0.4: 143 tokens, 24.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.14s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.15s/it]

193/450 respite_universe / weekends / blend / lambda=0.0: 203 tokens, 27.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.04s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.04s/it]

194/450 respite_universe / weekends / vote / lambda=0.0: 87 tokens, 21.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.26s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.26s/it]

195/450 respite_universe / weekends / schedule / lambda=0.0: 203 tokens, 27.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.21s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.21s/it]

196/450 respite_universe / weekends / blend / lambda=0.4: 203 tokens, 27.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.79s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.79s/it]

197/450 respite_universe / weekends / vote / lambda=0.4: 204 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.79s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.80s/it]

198/450 respite_universe / weekends / schedule / lambda=0.4: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.54s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.54s/it]

199/450 respite_universe / good_life / blend / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.56s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.56s/it]

200/450 respite_universe / good_life / vote / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

201/450 respite_universe / good_life / schedule / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.56s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.56s/it]

202/450 respite_universe / good_life / blend / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.61s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.61s/it]

203/450 respite_universe / good_life / vote / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.60s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.60s/it]

204/450 respite_universe / good_life / schedule / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

205/450 respite_universe / weather / blend / lambda=0.0: 205 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.60s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.60s/it]

206/450 respite_universe / weather / vote / lambda=0.0: 142 tokens, 24.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.41s/it]

207/450 respite_universe / weather / schedule / lambda=0.0: 206 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.47s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.47s/it]

208/450 respite_universe / weather / blend / lambda=0.4: 121 tokens, 24.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.74s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.74s/it]

209/450 respite_universe / weather / vote / lambda=0.4: 25 tokens, 11.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.57s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.57s/it]

210/450 respite_universe / weather / schedule / lambda=0.4: 139 tokens, 24.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.92s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.92s/it]

211/450 passing_dawn / short_story / blend / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.95s/it]

212/450 passing_dawn / short_story / vote / lambda=0.0: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.89s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.89s/it]

213/450 passing_dawn / short_story / schedule / lambda=0.0: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.88s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.88s/it]

214/450 passing_dawn / short_story / blend / lambda=0.4: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:23<00:00, 23.99s/it]

100%|█████████████████████████████████████████████| 1/1 [00:23<00:00, 23.99s/it]

215/450 passing_dawn / short_story / vote / lambda=0.4: 121 tokens, 24.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.93s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.93s/it]

216/450 passing_dawn / short_story / schedule / lambda=0.4: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

217/450 passing_dawn / favorite_place / blend / lambda=0.0: 206 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.36s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.36s/it]

218/450 passing_dawn / favorite_place / vote / lambda=0.0: 48 tokens, 13.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.38s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.38s/it]

219/450 passing_dawn / favorite_place / schedule / lambda=0.0: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.38s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.38s/it]

220/450 passing_dawn / favorite_place / blend / lambda=0.4: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.46s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.46s/it]

221/450 passing_dawn / favorite_place / vote / lambda=0.4: 137 tokens, 24.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.39s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.39s/it]

222/450 passing_dawn / favorite_place / schedule / lambda=0.4: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.95s/it]

223/450 passing_dawn / weekends / blend / lambda=0.0: 203 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.53s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.53s/it]

224/450 passing_dawn / weekends / vote / lambda=0.0: 117 tokens, 24.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.77s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.77s/it]

225/450 passing_dawn / weekends / schedule / lambda=0.0: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

226/450 passing_dawn / weekends / blend / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.92s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.92s/it]

227/450 passing_dawn / weekends / vote / lambda=0.4: 28 tokens, 11.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.94s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.94s/it]

228/450 passing_dawn / weekends / schedule / lambda=0.4: 203 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.72s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.72s/it]

229/450 passing_dawn / good_life / blend / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.24s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.24s/it]

230/450 passing_dawn / good_life / vote / lambda=0.0: 106 tokens, 21.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

231/450 passing_dawn / good_life / schedule / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.21s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.21s/it]

232/450 passing_dawn / good_life / blend / lambda=0.4: 205 tokens, 27.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.73s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.73s/it]

233/450 passing_dawn / good_life / vote / lambda=0.4: 142 tokens, 24.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.08s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.08s/it]

234/450 passing_dawn / good_life / schedule / lambda=0.4: 205 tokens, 27.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.85s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.85s/it]

235/450 passing_dawn / weather / blend / lambda=0.0: 205 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.49s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.49s/it]

236/450 passing_dawn / weather / vote / lambda=0.0: 102 tokens, 21.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.79s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.79s/it]

237/450 passing_dawn / weather / schedule / lambda=0.0: 205 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

238/450 passing_dawn / weather / blend / lambda=0.4: 205 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.33s/it]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.33s/it]

239/450 passing_dawn / weather / vote / lambda=0.4: 59 tokens, 17.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.98s/it]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.98s/it]

240/450 passing_dawn / weather / schedule / lambda=0.4: 90 tokens, 21.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.12s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.12s/it]

241/450 town_flood / short_story / blend / lambda=0.0: 202 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.32s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.32s/it]

242/450 town_flood / short_story / vote / lambda=0.0: 46 tokens, 13.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.01s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.01s/it]

243/450 town_flood / short_story / schedule / lambda=0.0: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.15s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.15s/it]

244/450 town_flood / short_story / blend / lambda=0.4: 202 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.98s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.98s/it]

245/450 town_flood / short_story / vote / lambda=0.4: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.96s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.96s/it]

246/450 town_flood / short_story / schedule / lambda=0.4: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

247/450 town_flood / favorite_place / blend / lambda=0.0: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.42s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.42s/it]

248/450 town_flood / favorite_place / vote / lambda=0.0: 48 tokens, 13.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.28s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.28s/it]

249/450 town_flood / favorite_place / schedule / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.33s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.33s/it]

250/450 town_flood / favorite_place / blend / lambda=0.4: 129 tokens, 24.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

251/450 town_flood / favorite_place / vote / lambda=0.4: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.25s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.26s/it]

252/450 town_flood / favorite_place / schedule / lambda=0.4: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.01s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.01s/it]

253/450 town_flood / weekends / blend / lambda=0.0: 203 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.61s/it]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.61s/it]

254/450 town_flood / weekends / vote / lambda=0.0: 32 tokens, 12.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

255/450 town_flood / weekends / schedule / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.10s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.10s/it]

256/450 town_flood / weekends / blend / lambda=0.4: 203 tokens, 27.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.21s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.21s/it]

257/450 town_flood / weekends / vote / lambda=0.4: 61 tokens, 18.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

258/450 town_flood / weekends / schedule / lambda=0.4: 200 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

259/450 town_flood / good_life / blend / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.45s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.45s/it]

260/450 town_flood / good_life / vote / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.61s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.61s/it]

261/450 town_flood / good_life / schedule / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.47s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.47s/it]

262/450 town_flood / good_life / blend / lambda=0.4: 125 tokens, 24.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.94s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.94s/it]

263/450 town_flood / good_life / vote / lambda=0.4: 28 tokens, 11.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.66s/it]

264/450 town_flood / good_life / schedule / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.96s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.96s/it]

265/450 town_flood / weather / blend / lambda=0.0: 205 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.23s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.23s/it]

266/450 town_flood / weather / vote / lambda=0.0: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.03s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.04s/it]

267/450 town_flood / weather / schedule / lambda=0.0: 205 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.15s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.15s/it]

268/450 town_flood / weather / blend / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.22s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.22s/it]

269/450 town_flood / weather / vote / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

270/450 town_flood / weather / schedule / lambda=0.4: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

271/450 sorrow_dawn / short_story / blend / lambda=0.0: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 26.00s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 26.00s/it]

272/450 sorrow_dawn / short_story / vote / lambda=0.0: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.85s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.85s/it]

273/450 sorrow_dawn / short_story / schedule / lambda=0.0: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.73s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.73s/it]

274/450 sorrow_dawn / short_story / blend / lambda=0.4: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.83s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.83s/it]

275/450 sorrow_dawn / short_story / vote / lambda=0.4: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

276/450 sorrow_dawn / short_story / schedule / lambda=0.4: 200 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

277/450 sorrow_dawn / favorite_place / blend / lambda=0.0: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.66s/it]

278/450 sorrow_dawn / favorite_place / vote / lambda=0.0: 24 tokens, 11.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.69s/it]

279/450 sorrow_dawn / favorite_place / schedule / lambda=0.0: 205 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

280/450 sorrow_dawn / favorite_place / blend / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.77s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.78s/it]

281/450 sorrow_dawn / favorite_place / vote / lambda=0.4: 27 tokens, 11.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.35s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.35s/it]

282/450 sorrow_dawn / favorite_place / schedule / lambda=0.4: 130 tokens, 24.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.86s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.86s/it]

283/450 sorrow_dawn / weekends / blend / lambda=0.0: 203 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.17s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.17s/it]

284/450 sorrow_dawn / weekends / vote / lambda=0.0: 203 tokens, 27.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

285/450 sorrow_dawn / weekends / schedule / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

286/450 sorrow_dawn / weekends / blend / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.78s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.78s/it]

287/450 sorrow_dawn / weekends / vote / lambda=0.4: 204 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.67s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.67s/it]

288/450 sorrow_dawn / weekends / schedule / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.45s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.45s/it]

289/450 sorrow_dawn / good_life / blend / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.56s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.57s/it]

290/450 sorrow_dawn / good_life / vote / lambda=0.0: 202 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

291/450 sorrow_dawn / good_life / schedule / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.51s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.51s/it]

292/450 sorrow_dawn / good_life / blend / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.68s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.68s/it]

293/450 sorrow_dawn / good_life / vote / lambda=0.4: 97 tokens, 21.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.64s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

294/450 sorrow_dawn / good_life / schedule / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

295/450 sorrow_dawn / weather / blend / lambda=0.0: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.27s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.27s/it]

296/450 sorrow_dawn / weather / vote / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.36s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.36s/it]

297/450 sorrow_dawn / weather / schedule / lambda=0.0: 194 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.22s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.22s/it]

298/450 sorrow_dawn / weather / blend / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:08<00:00,  8.39s/it]

100%|█████████████████████████████████████████████| 1/1 [00:08<00:00,  8.39s/it]

299/450 sorrow_dawn / weather / vote / lambda=0.4: 17 tokens, 8.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

300/450 sorrow_dawn / weather / schedule / lambda=0.4: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

301/450 peace_fury / short_story / blend / lambda=0.0: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.16s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.16s/it]

302/450 peace_fury / short_story / vote / lambda=0.0: 71 tokens, 18.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.82s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.82s/it]

303/450 peace_fury / short_story / schedule / lambda=0.0: 201 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

304/450 peace_fury / short_story / blend / lambda=0.4: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.86s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.86s/it]

305/450 peace_fury / short_story / vote / lambda=0.4: 188 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

306/450 peace_fury / short_story / schedule / lambda=0.4: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.20s/it]

307/450 peace_fury / favorite_place / blend / lambda=0.0: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.23s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.23s/it]

308/450 peace_fury / favorite_place / vote / lambda=0.0: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.38s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.39s/it]

309/450 peace_fury / favorite_place / schedule / lambda=0.0: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

310/450 peace_fury / favorite_place / blend / lambda=0.4: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.72s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.72s/it]

311/450 peace_fury / favorite_place / vote / lambda=0.4: 26 tokens, 11.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.87s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.87s/it]

312/450 peace_fury / favorite_place / schedule / lambda=0.4: 209 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.65s/it]

313/450 peace_fury / weekends / blend / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.14s/it]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.15s/it]

314/450 peace_fury / weekends / vote / lambda=0.0: 78 tokens, 19.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.78s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.78s/it]

315/450 peace_fury / weekends / schedule / lambda=0.0: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

316/450 peace_fury / weekends / blend / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.85s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.85s/it]

317/450 peace_fury / weekends / vote / lambda=0.4: 203 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.71s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.71s/it]

318/450 peace_fury / weekends / schedule / lambda=0.4: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

319/450 peace_fury / good_life / blend / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.07s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.07s/it]

320/450 peace_fury / good_life / vote / lambda=0.0: 197 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.49s/it]

321/450 peace_fury / good_life / schedule / lambda=0.0: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

322/450 peace_fury / good_life / blend / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.11s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.11s/it]

323/450 peace_fury / good_life / vote / lambda=0.4: 169 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

324/450 peace_fury / good_life / schedule / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.84s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.84s/it]

325/450 peace_fury / weather / blend / lambda=0.0: 204 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.25s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.25s/it]

326/450 peace_fury / weather / vote / lambda=0.0: 139 tokens, 24.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.24s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.25s/it]

327/450 peace_fury / weather / schedule / lambda=0.0: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

328/450 peace_fury / weather / blend / lambda=0.4: 207 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.90s/it]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.90s/it]

329/450 peace_fury / weather / vote / lambda=0.4: 97 tokens, 16.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.73s/it]

330/450 peace_fury / weather / schedule / lambda=0.4: 205 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.71s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.71s/it]

331/450 quarrel_peace / short_story / blend / lambda=0.0: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.72s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.72s/it]

332/450 quarrel_peace / short_story / vote / lambda=0.0: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.77s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.77s/it]

333/450 quarrel_peace / short_story / schedule / lambda=0.0: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.76s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.76s/it]

334/450 quarrel_peace / short_story / blend / lambda=0.4: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.79s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.80s/it]

335/450 quarrel_peace / short_story / vote / lambda=0.4: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.83s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.83s/it]

336/450 quarrel_peace / short_story / schedule / lambda=0.4: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.18s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.18s/it]

337/450 quarrel_peace / favorite_place / blend / lambda=0.0: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.82s/it]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.82s/it]

338/450 quarrel_peace / favorite_place / vote / lambda=0.0: 94 tokens, 20.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.68s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.68s/it]

339/450 quarrel_peace / favorite_place / schedule / lambda=0.0: 205 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

340/450 quarrel_peace / favorite_place / blend / lambda=0.4: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.00s/it]

100%|█████████████████████████████████████████████| 1/1 [00:19<00:00, 19.00s/it]

341/450 quarrel_peace / favorite_place / vote / lambda=0.4: 83 tokens, 19.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.55s/it]

342/450 quarrel_peace / favorite_place / schedule / lambda=0.4: 204 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.95s/it]

343/450 quarrel_peace / weekends / blend / lambda=0.0: 203 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.78s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.78s/it]

344/450 quarrel_peace / weekends / vote / lambda=0.0: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

345/450 quarrel_peace / weekends / schedule / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.80s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.80s/it]

346/450 quarrel_peace / weekends / blend / lambda=0.4: 205 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.52s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.52s/it]

347/450 quarrel_peace / weekends / vote / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.90s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.90s/it]

348/450 quarrel_peace / weekends / schedule / lambda=0.4: 203 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.36s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.37s/it]

349/450 quarrel_peace / good_life / blend / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.58s/it]

100%|█████████████████████████████████████████████| 1/1 [00:21<00:00, 21.58s/it]

350/450 quarrel_peace / good_life / vote / lambda=0.0: 101 tokens, 21.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

351/450 quarrel_peace / good_life / schedule / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.13s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.13s/it]

352/450 quarrel_peace / good_life / blend / lambda=0.4: 209 tokens, 27.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.87s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.87s/it]

353/450 quarrel_peace / good_life / vote / lambda=0.4: 185 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

354/450 quarrel_peace / good_life / schedule / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

355/450 quarrel_peace / weather / blend / lambda=0.0: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.13s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.13s/it]

356/450 quarrel_peace / weather / vote / lambda=0.0: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.22s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.22s/it]

357/450 quarrel_peace / weather / schedule / lambda=0.0: 206 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.05s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.05s/it]

358/450 quarrel_peace / weather / blend / lambda=0.4: 205 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.50s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.50s/it]

359/450 quarrel_peace / weather / vote / lambda=0.4: 173 tokens, 25.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.15s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.15s/it]

360/450 quarrel_peace / weather / schedule / lambda=0.4: 204 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.63s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.63s/it]

361/450 fury_flood / short_story / blend / lambda=0.0: 202 tokens, 25.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

362/450 fury_flood / short_story / vote / lambda=0.0: 201 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.64s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.64s/it]

363/450 fury_flood / short_story / schedule / lambda=0.0: 200 tokens, 25.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.66s/it]

364/450 fury_flood / short_story / blend / lambda=0.4: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.70s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.70s/it]

365/450 fury_flood / short_story / vote / lambda=0.4: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.68s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

366/450 fury_flood / short_story / schedule / lambda=0.4: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.57s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.57s/it]

367/450 fury_flood / favorite_place / blend / lambda=0.0: 205 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:07<00:00,  7.95s/it]

100%|█████████████████████████████████████████████| 1/1 [00:07<00:00,  7.95s/it]

368/450 fury_flood / favorite_place / vote / lambda=0.0: 9 tokens, 7.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.29s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.29s/it]

369/450 fury_flood / favorite_place / schedule / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.15s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.15s/it]

370/450 fury_flood / favorite_place / blend / lambda=0.4: 124 tokens, 24.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.72s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.72s/it]

371/450 fury_flood / favorite_place / vote / lambda=0.4: 26 tokens, 11.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 26.00s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 26.00s/it]

372/450 fury_flood / favorite_place / schedule / lambda=0.4: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.75s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.75s/it]

373/450 fury_flood / weekends / blend / lambda=0.0: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.74s/it]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.75s/it]

374/450 fury_flood / weekends / vote / lambda=0.0: 49 tokens, 16.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.67s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.68s/it]

375/450 fury_flood / weekends / schedule / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.82s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.82s/it]

376/450 fury_flood / weekends / blend / lambda=0.4: 203 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.22s/it]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.22s/it]

377/450 fury_flood / weekends / vote / lambda=0.4: 54 tokens, 17.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.85s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.85s/it]

378/450 fury_flood / weekends / schedule / lambda=0.4: 203 tokens, 26.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.31s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.31s/it]

379/450 fury_flood / good_life / blend / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.34s/it]

380/450 fury_flood / good_life / vote / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

381/450 fury_flood / good_life / schedule / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.44s/it]

382/450 fury_flood / good_life / blend / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

383/450 fury_flood / good_life / vote / lambda=0.4: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.42s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.42s/it]

384/450 fury_flood / good_life / schedule / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

385/450 fury_flood / weather / blend / lambda=0.0: 206 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.65s/it]

386/450 fury_flood / weather / vote / lambda=0.0: 24 tokens, 11.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.19s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.19s/it]

387/450 fury_flood / weather / schedule / lambda=0.0: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.08s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.08s/it]

388/450 fury_flood / weather / blend / lambda=0.4: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.94s/it]

100%|█████████████████████████████████████████████| 1/1 [00:16<00:00, 16.94s/it]

389/450 fury_flood / weather / vote / lambda=0.4: 56 tokens, 16.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.21s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.21s/it]

390/450 fury_flood / weather / schedule / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.62s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.63s/it]

391/450 education_initiation / short_story / blend / lambda=0.0: 202 tokens, 25.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.10s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.10s/it]

392/450 education_initiation / short_story / vote / lambda=0.0: 44 tokens, 13.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.03s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.03s/it]

393/450 education_initiation / short_story / schedule / lambda=0.0: 202 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.65s/it]

394/450 education_initiation / short_story / blend / lambda=0.4: 108 tokens, 20.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.77s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.77s/it]

395/450 education_initiation / short_story / vote / lambda=0.4: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.89s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.89s/it]

396/450 education_initiation / short_story / schedule / lambda=0.4: 202 tokens, 25.9s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

397/450 education_initiation / favorite_place / blend / lambda=0.0: 205 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.70s/it]

100%|█████████████████████████████████████████████| 1/1 [00:11<00:00, 11.70s/it]

398/450 education_initiation / favorite_place / vote / lambda=0.0: 30 tokens, 11.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.14s/it]

399/450 education_initiation / favorite_place / schedule / lambda=0.0: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.12s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.12s/it]

400/450 education_initiation / favorite_place / blend / lambda=0.4: 124 tokens, 24.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.25s/it]

100%|█████████████████████████████████████████████| 1/1 [00:18<00:00, 18.25s/it]

401/450 education_initiation / favorite_place / vote / lambda=0.4: 72 tokens, 18.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.13s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.13s/it]

402/450 education_initiation / favorite_place / schedule / lambda=0.4: 204 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.74s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.74s/it]

403/450 education_initiation / weekends / blend / lambda=0.0: 203 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.66s/it]

404/450 education_initiation / weekends / vote / lambda=0.0: 34 tokens, 12.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.61s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.61s/it]

405/450 education_initiation / weekends / schedule / lambda=0.0: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.98s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.98s/it]

406/450 education_initiation / weekends / blend / lambda=0.4: 203 tokens, 27.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.69s/it]

407/450 education_initiation / weekends / vote / lambda=0.4: 34 tokens, 12.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

408/450 education_initiation / weekends / schedule / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.32s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.32s/it]

409/450 education_initiation / good_life / blend / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

410/450 education_initiation / good_life / vote / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

411/450 education_initiation / good_life / schedule / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.39s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.39s/it]

412/450 education_initiation / good_life / blend / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.40s/it]

413/450 education_initiation / good_life / vote / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.37s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.37s/it]

414/450 education_initiation / good_life / schedule / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.75s/it]

100%|█████████████████████████████████████████████| 1/1 [00:20<00:00, 20.75s/it]

415/450 education_initiation / weather / blend / lambda=0.0: 92 tokens, 20.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.26s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.26s/it]

416/450 education_initiation / weather / vote / lambda=0.0: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.15s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.15s/it]

417/450 education_initiation / weather / schedule / lambda=0.0: 204 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.17s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.17s/it]

418/450 education_initiation / weather / blend / lambda=0.4: 133 tokens, 24.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.02s/it]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.02s/it]

419/450 education_initiation / weather / vote / lambda=0.4: 57 tokens, 17.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.97s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.97s/it]

420/450 education_initiation / weather / schedule / lambda=0.4: 175 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.65s/it]

421/450 respite_peace / short_story / blend / lambda=0.0: 202 tokens, 25.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.77s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.77s/it]

422/450 respite_peace / short_story / vote / lambda=0.0: 202 tokens, 25.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.65s/it]

423/450 respite_peace / short_story / schedule / lambda=0.0: 202 tokens, 25.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.65s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.65s/it]

424/450 respite_peace / short_story / blend / lambda=0.4: 202 tokens, 25.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.66s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.66s/it]

425/450 respite_peace / short_story / vote / lambda=0.4: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

100%|█████████████████████████████████████████████| 1/1 [00:25<00:00, 25.69s/it]

426/450 respite_peace / short_story / schedule / lambda=0.4: 202 tokens, 25.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.05s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.05s/it]

427/450 respite_peace / favorite_place / blend / lambda=0.0: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.97s/it]

100%|█████████████████████████████████████████████| 1/1 [00:12<00:00, 12.97s/it]

428/450 respite_peace / favorite_place / vote / lambda=0.0: 40 tokens, 13.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.01s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.01s/it]

429/450 respite_peace / favorite_place / schedule / lambda=0.0: 205 tokens, 26.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.33s/it]

430/450 respite_peace / favorite_place / blend / lambda=0.4: 205 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.36s/it]

100%|█████████████████████████████████████████████| 1/1 [00:17<00:00, 17.36s/it]

431/450 respite_peace / favorite_place / vote / lambda=0.4: 64 tokens, 17.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.70s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.70s/it]

432/450 respite_peace / favorite_place / schedule / lambda=0.4: 205 tokens, 26.7s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.41s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.42s/it]

433/450 respite_peace / weekends / blend / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.26s/it]

100%|█████████████████████████████████████████████| 1/1 [00:24<00:00, 24.26s/it]

434/450 respite_peace / weekends / vote / lambda=0.0: 118 tokens, 24.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.28s/it]

100%|█████████████████████████████████████████████| 1/1 [00:27<00:00, 27.28s/it]

435/450 respite_peace / weekends / schedule / lambda=0.0: 210 tokens, 27.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.43s/it]

436/450 respite_peace / weekends / blend / lambda=0.4: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

437/450 respite_peace / weekends / vote / lambda=0.4: 203 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.48s/it]

438/450 respite_peace / weekends / schedule / lambda=0.4: 203 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.39s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.39s/it]

439/450 respite_peace / good_life / blend / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.29s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.29s/it]

440/450 respite_peace / good_life / vote / lambda=0.0: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.35s/it]

441/450 respite_peace / good_life / schedule / lambda=0.0: 203 tokens, 26.4s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

442/450 respite_peace / good_life / blend / lambda=0.4: 204 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.78s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.78s/it]

443/450 respite_peace / good_life / vote / lambda=0.4: 205 tokens, 26.8s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.30s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.30s/it]

444/450 respite_peace / good_life / schedule / lambda=0.4: 203 tokens, 26.3s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.59s/it]

445/450 respite_peace / weather / blend / lambda=0.0: 205 tokens, 26.6s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.23s/it]

100%|█████████████████████████████████████████████| 1/1 [00:13<00:00, 13.23s/it]

446/450 respite_peace / weather / vote / lambda=0.0: 48 tokens, 13.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

447/450 respite_peace / weather / schedule / lambda=0.0: 205 tokens, 26.5s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.09s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.09s/it]

448/450 respite_peace / weather / blend / lambda=0.4: 205 tokens, 26.1s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.24s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.24s/it]

449/450 respite_peace / weather / vote / lambda=0.4: 205 tokens, 26.2s

  0%|                                                     | 0/1 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

100%|█████████████████████████████████████████████| 1/1 [00:26<00:00, 26.50s/it]

450/450 respite_peace / weather / schedule / lambda=0.4: 207 tokens, 26.5s

## Whole-continuation summary

Summary rows retain pair identity and aggregate over prompts. Positive joint
values mean both concepts improved relative to the prompt-matched baseline.
Length fields use actual re-tokenized continuations, exposing the historical
one-seed-token offset and early EOS rather than assuming it away.

In [8]:
parsed = read_records(LOG_PATH)
result_rows = []
for record in parsed:
    config = record["config"]
    expression = record["expression"]
    angles = record["angles"]
    da = expression[config["a"]]["delta"]
    db = expression[config["b"]]["delta"]
    ca = angles[config["a"]]["delta"]["token_cos"]
    cb = angles[config["b"]]["delta"]["token_cos"]
    metadata = record.get("metadata", {})
    result_rows.append(
        {
            "pair_id": config["pair_id"],
            "prompt_id": config["prompt_id"],
            "a": config["a"],
            "b": config["b"],
            "rho": config["rho_model"],
            "method": config["method"],
            "lam": config["lam"],
            "joint_expression": min(da, db),
            "both_positive_expression": min(da, db) > 0,
            "joint_token_cos": min(ca, cb),
            "both_positive_token_cos": min(ca, cb) > 0,
            "ppl_ratio": record["ppl_ratio"],
            "continuation_tokens": metadata.get("token_count"),
            "termination": metadata.get("termination"),
            "distinct_token_ratio": metadata.get("distinct_token_ratio"),
            "repeated_4gram_rate": metadata.get("repeated_ngram_rate"),
            "max_repeated_span_tokens": metadata.get(
                "max_repeated_span_tokens"
            ),
            "elapsed_seconds": metadata.get("elapsed_seconds"),
        }
    )

results = pd.DataFrame(result_rows)
summary = pd.DataFrame()
if not results.empty:
    summary = (
        results.groupby(
            ["pair_id", "a", "b", "rho", "method", "lam"],
            dropna=False,
        )
        .agg(
            joint_expression=("joint_expression", "mean"),
            both_positive_expression=("both_positive_expression", "mean"),
            joint_token_cos=("joint_token_cos", "mean"),
            both_positive_token_cos=("both_positive_token_cos", "mean"),
            ppl_ratio=("ppl_ratio", "mean"),
            continuation_tokens=("continuation_tokens", "mean"),
            distinct_token_ratio=("distinct_token_ratio", "mean"),
            repeated_4gram_rate=("repeated_4gram_rate", "mean"),
            max_repeated_span_tokens=("max_repeated_span_tokens", "mean"),
            elapsed_seconds=("elapsed_seconds", "mean"),
            n_prompts=("prompt_id", "nunique"),
        )
        .reset_index()
    )
    summary["observed_records"] = len(results)
    summary["expected_records"] = active_cells
    summary["complete"] = len(results) == active_cells
    summary.to_csv(SUMMARY_PATH, index=False)
    display(
        results.groupby(["method", "lam"])
        .agg(
            joint_cos=("joint_token_cos", "mean"),
            both_positive=("both_positive_token_cos", "mean"),
            ppl_ratio=("ppl_ratio", "mean"),
            repeated_4gram=("repeated_4gram_rate", "mean"),
            tokens=("continuation_tokens", "mean"),
            n=("pair_id", "size"),
        )
        .round(4)
    )
    print(f"wrote {SUMMARY_PATH}; completeness {len(results)}/{active_cells}")
else:
    print(f"no records at {LOG_PATH}; generation remains disabled")

              joint_cos  both_positive  ppl_ratio  repeated_4gram    tokens  \
method   lam
blend    0.0     0.0151         0.8533     3.9514          0.3677  197.2800
         0.4     0.0142         0.8267     2.6876          0.2954  189.6667
schedule 0.0     0.0179         0.8933     3.7186          0.3458  203.5067
         0.4     0.0128         0.8267     2.3347          0.2844  194.2000
vote     0.0     0.0153         0.9467    10.5869          0.2541  123.5333
         0.4     0.0106         0.8400     5.4540          0.1657  127.2667

               n
method   lam
blend    0.0  75
         0.4  75
schedule 0.0  75
         0.4  75
vote     0.0  75
         0.4  75

wrote resources/53_long_composition_summary.csv; completeness 450/450

## Optional 20-token trajectories

`RUN_TRAJECTORIES` performs one hidden-state pass per continuation and
baseline, then computes bin-level FRH expression and token-to-subspace cosine
from those hidden states. Baseline subtraction is reported only for bins with
tokens on both sides, with explicit coverage. Segment PPL is also recorded.
This is separate from generation so the expensive analysis can be resumed.

In [9]:
def token_hidden(text):
    tokens = fur.model.tokenize(text)
    with torch.inference_mode():
        hidden = fur.model.forward_last_hiden_state(tokens).squeeze(0)
    ids = tokens.squeeze(0).tolist()
    bos_id = fur.model.tokenizer.bos_token_id
    if ids and ids[0] == bos_id:
        ids = ids[1:]
        hidden = hidden[1:]
    return ids, hidden


def binned_values(ids, hidden, concept_map):
    bins = token_bins(ids, BIN_WIDTH)
    if not bins:
        return {}
    values = {part.index: {"bin": part} for part in bins}
    for name, concept in concept_map.items():
        projected = fur._project_hidden_states(
            hidden.unsqueeze(0), concept
        ).reshape(len(ids), -1).float().mean(-1)
        cosine = vector_subspace_cosine(
            hidden, concept.tensor.squeeze(0)
        ).float()
        for part in bins:
            values[part.index][name] = {
                "expression": float(projected[part.start : part.stop].mean()),
                "token_cos": float(cosine[part.start : part.stop].mean()),
            }
    return values


def segment_perplexity(token_ids):
    if len(token_ids) < 2:
        return float("nan")
    return harness.perplexity(fur.model.tokenizer.decode(token_ids))


trajectory_rows = []
if RUN_TRAJECTORIES:
    baseline_hidden = {}
    baseline_ppl = {}
    for record_index, record in enumerate(parsed, start=1):
        config = record["config"]
        prompt_id = config["prompt_id"]
        concept_map = {
            config["a"]: concepts[config["a"]],
            config["b"]: concepts[config["b"]],
        }
        steered_ids, steered_hidden = token_hidden(record["continuation"])
        steered = binned_values(steered_ids, steered_hidden, concept_map)
        if prompt_id not in baseline_hidden:
            baseline_continuation = harness.continuation(
                baseline_texts_by_id[prompt_id], prompts_by_id[prompt_id]
            )
            baseline_hidden[prompt_id] = token_hidden(baseline_continuation)
        base_ids, base_hidden = baseline_hidden[prompt_id]
        baseline = binned_values(base_ids, base_hidden, concept_map)

        for bin_index in sorted(set(steered) & set(baseline)):
            sbin = steered[bin_index]["bin"]
            bbin = baseline[bin_index]["bin"]
            bppl_key = (prompt_id, bin_index)
            if bppl_key not in baseline_ppl:
                baseline_ppl[bppl_key] = segment_perplexity(bbin.token_ids)
            segment_ppl = segment_perplexity(sbin.token_ids)
            row = {
                "pair_id": config["pair_id"],
                "prompt_id": prompt_id,
                "method": config["method"],
                "lam": config["lam"],
                "bin": bin_index,
                "start_token": sbin.start,
                "stop_token": sbin.stop,
                "coverage": min(len(sbin.token_ids), len(bbin.token_ids))
                / BIN_WIDTH,
                "segment_ppl": segment_ppl,
                "baseline_segment_ppl": baseline_ppl[bppl_key],
                "segment_ppl_ratio": segment_ppl / baseline_ppl[bppl_key],
            }
            for label, name in (("a", config["a"]), ("b", config["b"])):
                row[f"{label}_expression_steered"] = steered[bin_index][name][
                    "expression"
                ]
                row[f"{label}_expression_baseline"] = baseline[bin_index][name][
                    "expression"
                ]
                row[f"{label}_expression_delta"] = (
                    row[f"{label}_expression_steered"]
                    - row[f"{label}_expression_baseline"]
                )
                row[f"{label}_token_cos_steered"] = steered[bin_index][name][
                    "token_cos"
                ]
                row[f"{label}_token_cos_baseline"] = baseline[bin_index][name][
                    "token_cos"
                ]
                row[f"{label}_token_cos_delta"] = (
                    row[f"{label}_token_cos_steered"]
                    - row[f"{label}_token_cos_baseline"]
                )
            row["joint_expression_delta"] = min(
                row["a_expression_delta"], row["b_expression_delta"]
            )
            row["joint_token_cos_delta"] = min(
                row["a_token_cos_delta"], row["b_token_cos_delta"]
            )
            if config["method"] == "schedule":
                scored_positions = range(max(1, sbin.start), sbin.stop)
                active = [(position - 1) % 2 for position in scored_positions]
                row["schedule_a_fraction"] = (
                    active.count(0) / len(active) if active else float("nan")
                )
            else:
                row["schedule_a_fraction"] = float("nan")
            trajectory_rows.append(row)
        del steered_hidden
        if record_index % 10 == 0:
            torch.cuda.empty_cache()
            print(f"trajectory {record_index}/{len(parsed)}")

    trajectories = pd.DataFrame(trajectory_rows)
    trajectories.to_csv(TRAJECTORY_PATH, index=False)
    print(f"wrote {len(trajectories)} rows to {TRAJECTORY_PATH}")
    if not trajectories.empty:
        trajectory_summary = (
            trajectories.groupby(["method", "lam", "bin"])
            .agg(
                joint_token_cos=("joint_token_cos_delta", "mean"),
                joint_expression=("joint_expression_delta", "mean"),
                segment_ppl_ratio=("segment_ppl_ratio", "mean"),
                coverage=("coverage", "mean"),
            )
            .reset_index()
        )
        fig, axes = plt.subplots(1, 3, figsize=(14.5, 4.2))
        for axis, metric, ylabel in zip(
            axes,
            ("joint_token_cos", "joint_expression", "segment_ppl_ratio"),
            (
                "joint token-cosine delta",
                "joint expression delta",
                "segment PPL ratio",
            ),
        ):
            for (method, lam), cell in trajectory_summary.groupby(
                ["method", "lam"]
            ):
                axis.plot(
                    cell["bin"] * BIN_WIDTH,
                    cell[metric],
                    marker="o",
                    label=f"{method}, lambda={lam}",
                )
            axis.set_xlabel("continuation token position")
            axis.set_ylabel(ylabel)
        axes[0].axhline(0, color="gray", linewidth=0.8)
        axes[1].axhline(0, color="gray", linewidth=0.8)
        axes[0].legend(fontsize=7)
        plt.tight_layout()
        plt.savefig(TRAJECTORY_FIGURE_PATH, dpi=150)
        plt.show()

        final_bins = (
            trajectories.sort_values("bin")
            .groupby(["pair_id", "prompt_id", "method", "lam"])
            .tail(1)
            .groupby(["pair_id", "method", "lam"])
            .agg(
                final_joint_expression=("joint_expression_delta", "mean"),
                final_joint_token_cos=("joint_token_cos_delta", "mean"),
                final_segment_ppl_ratio=("segment_ppl_ratio", "mean"),
                final_bin_coverage=("coverage", "mean"),
            )
            .reset_index()
        )
        summary = summary.merge(
            final_bins, on=["pair_id", "method", "lam"], how="left"
        )
        summary.to_csv(SUMMARY_PATH, index=False)

trajectory 10/450

trajectory 20/450

trajectory 30/450

trajectory 40/450

trajectory 50/450

trajectory 60/450

trajectory 70/450

trajectory 80/450

trajectory 90/450

trajectory 100/450

trajectory 110/450

trajectory 120/450

trajectory 130/450

trajectory 140/450

trajectory 150/450

trajectory 160/450

trajectory 170/450

trajectory 180/450

trajectory 190/450

trajectory 200/450

trajectory 210/450

trajectory 220/450

trajectory 230/450

trajectory 240/450

trajectory 250/450

trajectory 260/450

trajectory 270/450

trajectory 280/450

trajectory 290/450

trajectory 300/450

trajectory 310/450

trajectory 320/450

trajectory 330/450

trajectory 340/450

trajectory 350/450

trajectory 360/450

trajectory 370/450

trajectory 380/450

trajectory 390/450

trajectory 400/450

trajectory 410/450

trajectory 420/450

trajectory 430/450

trajectory 440/450

trajectory 450/450
wrote 3101 rows to resources/53_long_composition_trajectories.csv

In [10]:
if not results.empty:
    plot_summary = (
        results.groupby(["method", "lam"])
        .agg(
            joint_token_cos=("joint_token_cos", "mean"),
            ppl_ratio=("ppl_ratio", "mean"),
            repeated_4gram_rate=("repeated_4gram_rate", "mean"),
        )
        .reset_index()
    )
    methods = list(METHODS)
    colors = {"blend": "tab:blue", "vote": "tab:orange", "schedule": "tab:green"}
    fig, axes = plt.subplots(1, 3, figsize=(14.5, 4.2))
    for axis, metric, ylabel in zip(
        axes,
        ("joint_token_cos", "ppl_ratio", "repeated_4gram_rate"),
        ("joint token-cosine delta", "continuation PPL ratio", "repeated 4-gram rate"),
    ):
        for method in methods:
            cell = plot_summary[plot_summary["method"] == method].sort_values(
                "lam"
            )
            axis.plot(
                cell["lam"],
                cell[metric],
                marker="o",
                label=method,
                color=colors[method],
            )
        axis.set_xlabel("fluency weight lambda")
        axis.set_ylabel(ylabel)
    axes[0].axhline(0, color="gray", linewidth=0.8)
    axes[1].axhline(2.5, color="gray", linestyle=":", linewidth=0.8)
    axes[0].legend()
    plt.tight_layout()
    plt.savefig(FIGURE_PATH, dpi=150)
    plt.show()

    qualitative = []
    for record in parsed:
        config = record["config"]
        qualitative.append(
            {
                "pair": config["pair_id"],
                "prompt": config["prompt_id"],
                "method": config["method"],
                "lambda": config["lam"],
                "continuation": record["continuation"],
            }
        )
    display(pd.DataFrame(qualitative))

,pair,prompt,method,lambda,continuation
0,education_sorrow,short_story,blend,0.0,"Once, on one storm-ravined coast there existed..."
1,education_sorrow,short_story,vote,0.0,"Once, in ancient Greece on Mount Ida, there ex..."
2,education_sorrow,short_story,schedule,0.0,"Once, on one storm-raged night in late October..."
3,education_sorrow,short_story,blend,0.4,"Once, in a small village surrounded by vast de..."
4,education_sorrow,short_story,vote,0.4,"Once, in a small coastal town surrounded only ..."
...,...,...,...,...,...
445,respite_peace,weather,vote,0.0,Today the weather is not something I can obser...
446,respite_peace,weather,schedule,0.0,Today the weather is not something I can direc...
447,respite_peace,weather,blend,0.4,Today the weather is not something I can direc...
448,respite_peace,weather,vote,0.4,Today the weather is not something I can obser...
449,respite_peace,weather,schedule,0.4,Today the weather is not something I can obser...